
# This file is automatically generated during the generation of setup.py
# Copyright 2020, Kangeras

author = 'Jason Dsouza: http://www.github.com/jasmcaus'
version = '0.1.8'
full_version = '0.1.8'
release = True
if not release:
    version = full_version
