
# This file is automatically generated during the generation of setup.py
# Copyright 2020, canaro
author = 'Jason Dsouza'
version = '1.0.2'
full_version = '1.0.2'
release = True
contributors = ['Jason Dsouza <jasmcaus@gmail.com>']
