
# This file is automatically generated during the generation of setup.py
# Copyright 2020, canaro
author = 'Jason Dsouza <jasmcaus@gmail.com>'
version = '1.0.9'
full_version = '1.0.9'
release = True
contributors = ['Jason Dsouza <jasmcaus@gmail.com>']
