
# This file is automatically generated during the generation of setup.py
# Copyright 2020, Canaro

author = 'Jason Dsouza: http://www.github.com/jasmcaus'
version = '1.0.6'
full_version = '1.0.6'
release = True
if not release:
    version = full_version
